service: beetlescraper-template-validator
frameworkVersion: '3'

provider:
  name: aws
  ecr:
    # In this section you can define images that will be built locally and uploaded to ECR
    images: 
      bts_validator_container:
        path: ./
  # runtime: python3.9
  stage: dev
  region: ap-south-1
  versionFunctions: false
  timeout: 60
  environment:
    BEETLE_SCRAPER_ENDPOINT: ${file(./config/config.${opt:stage, 'dev'}.json):BEETLE_SCRAPER_ENDPOINT}

functions:
  app:
    image:
      name: bts_validator_container

package:
  patterns:
    - '!venv/**'
    - '!__pycache__/**'
    - '!node_modules/**'
