service: beetlescraper-template-validator
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ap-south-1
  versionFunctions: false
  timeout: 60
  environment:
    BEETLE_SCRAPER_ENDPOINT: ${file(./config/config.${opt:stage, 'dev'}.json):BEETLE_SCRAPER_ENDPOINT}

functions:
  app:
    handler: handler.app

package:
  patterns:
    - '!venv/**'
    - '!__pycache__/**'
    - '!node_modules/**'

plugins:
  - serverless-python-requirements
